services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${AWS_S3_ACCESS_KEY_ID:-access_key}
      MINIO_ROOT_PASSWORD: ${AWS_S3_SECRET_ACCESS_KEY:-secret_access_key}
    command: server /data --console-address ":${AWS_S3_ADMIN_PORT:-9001}"
    ports:
      - "${AWS_S3_DEFAULT_PORT:-9000}:9000"
      - "${AWS_S3_ADMIN_PORT:-9001}:9001"
    volumes:
      - ./deploy/data/minio:/data
    networks:
      - postgres_network
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge